project_id = "orrdygxpeoenqaxevcjf"

[functions.analyze-medicine]
verify_jwt = false

[functions.verify-batch]
verify_jwt = false

[functions.process-qr-data]
verify_jwt = false

[functions.pharmacy-api]
verify_jwt = false
